removed delegate, added rx bindings;
skylab-main/ios pull request #33
Opened 2023-01-27 17:32 UTC by SerhiiMolodets

Замінив делегати на реактивний звʼязок, методи делегатів закоментив і залишив щоб було видно різницю.
Був оновлений звʼязок функцій openFirstSubcontroller, openSecondSubcontroller.
IBActions також закоментив вони більше не потрібні.
Зміни вніс тільки до FirstPageScene, щоб була можливість іншим учасникам попрактикуватись.
Корисна стаття https://www.uptech.team/blog/mvvm-coordinators-and-rxswift

2023-01-27 19:24 UTC, Dorogobid commented
Думаю, що PR треба робити в main. Гілка coordinator вже вмерджилась в основну. @alexdneprin виправ, якщо я помиляюся.

2023-01-27 19:24 UTC, Dorogobid approved these changes
Дуже круто!

2023-02-20 17:32 UTC, alexslkgit requested changes

2023-02-20 17:32 UTC, alexslkgit commented on Skylab/Scenes/FirstPageScene/FirstPageCoordinator.swift
> -
Question 1

2023-02-20 18:16 UTC, SerhiiMolodets commented on Skylab/Scenes/FirstPageScene/FirstPageCoordinator.swift
> +import RxSwift
В нас в координаторі РХ використовуєть для біндінгу з  viewModel стосовно навігації.
В кожній viewModel будть різні машрути тобто різні outputs, на які требі буде підписатися для реалізації в координаторі.
Погано розумію як це типізувати щоб написати батьківський координатор, ми ж  під делегати не пишемо, а це по суті той самий метод спілкування між обʼєктами просто реалізація відрізняється.
Чи я не так зрозумів ?

2023-02-20 18:26 UTC, SerhiiMolodets commented on Skylab/Scenes/FirstPageScene/FirstPageCoordinator.swift
> +    let bag = DisposeBag()
а це як раз і має бути в базовому класі )

2023-02-20 18:27 UTC, SerhiiMolodets commented on Skylab/Scenes/FirstPageScene/FirstPageCoordinator.swift
> +class FirstPageCoordinator: Coordinator {
Дякую буду мати на увазі.

2023-02-20 18:36 UTC, SerhiiMolodets commented on Skylab/Scenes/FirstPageScene/FirstPageCoordinator.swift
> +            .subscribe(onNext: { [weak self] in self?.openSecondSubController()} )
так це аналогічне, .subscribe(onNext: - це скорочений варіант .subscribe , ми просто відкидаємо 2 блоки onError і onCompleted, якщо нам не треба тут опрацювувати помилки чи викликати щось по завершенню.

2023-02-20 18:37 UTC, SerhiiMolodets commented on Skylab/Scenes/FirstPageScene/ViewModels/FirstPageViewModel.swift
> +//        Connection between input and output
блін це в мене якись баг , в мене всі коменти так ставляться)

2023-02-20 18:43 UTC, SerhiiMolodets commented on Skylab/Scenes/FirstPageScene/FirstPageCoordinator.swift
> +        //        MARK: - Observe to viewModel and call to func openFirstSubcontroller
ок, зрозумів

2023-02-20 18:45 UTC, SerhiiMolodets commented on Skylab/Scenes/FirstPageScene/ViewControllers/FirstPageViewController.swift
> +    let bag = DisposeBag()
так )

2023-02-20 18:49 UTC, SerhiiMolodets commented on Skylab/Scenes/FirstPageScene/ViewModels/FirstPageViewModel.swift
> +//        Connection between input and output
все пофіксив

2023-02-26 19:53 UTC, alexslkgit commented on Skylab/Scenes/FirstPageScene/FirstPageCoordinator.swift
> +import RxSwift
Все так, нехай в батькывському буде bag поки що

2023-02-26 19:56 UTC, alexslkgit approved these changes

2023-02-27 18:17 UTC, merged