SecondPageViewController changed to SecondPageSwiftUIView;
skylab-main/ios pull request #41
Opened 2023-01-30 20:08 UTC by SerhiiMolodets

Вдалось інтегрувати  SwiftUI screen, також налаштував звʼязок між навігаційною кнопкою, viewModel та Coordinator, згідно нашої архітектури.
Можливі проблеми коли треба буде спостерігати за данними з viewModel так як RxSwift ,на перший погляд, не "дружить" зі SwiftUI.

2023-02-26 20:11 UTC, alexslkgit requested changes

2023-02-26 20:11 UTC, alexslkgit commented on Skylab/Scenes/SecondPageScene/SecondPageCoordinator.swift
> +//        changed to RxSwift
Все ок, тільки давай с коментами наведемо порядок в цьому PR :) 
Потім можна мержити

2023-02-26 20:11 UTC, alexslkgit commented on Skylab/Scenes/SecondPageScene/SecondPageCoordinator.swift
> +//        changed to RxSwift
Маю на цвазі красиво оформити, плюс десь може додати пояснення що саме відбувається "тут ми робимо оце" "а тут робимо оце"...

2023-03-07 18:42 UTC, SerhiiMolodets commented on Skylab/Scenes/SecondPageScene/SecondPageCoordinator.swift
> +//        changed to RxSwift
прибрав сміття, додав марки з поясненнями

2023-03-16 18:11 UTC, SerhiiMolodets commented
Не зміг пофіксити.

2023-03-28 07:42 UTC, closed without merging

2023-03-28 07:42 UTC, SerhiiMolodets commented
зроблю нову гілку