Added viewModel to OnboardingController.
skylab-main/ios pull request #48
Opened 2023-02-16 21:06 UTC by artembilyy

😊

2023-02-16 21:38 UTC, tk4chenko commented
Awesome! 🥳🥳🥳

2023-02-17 07:16 UTC, Dorogobid commented on Skylab/Scenes/OnboardingScene/ViewControllers/OnboardingViewController.swift
> +        viewModel?.openAuthorizationController()
А для чого ця строчка?

2023-02-17 09:36 UTC, artembilyy commented on Skylab/Scenes/OnboardingScene/ViewControllers/OnboardingViewController.swift
> +        viewModel?.openAuthorizationController()
Для перевірки роботоздатності.

2023-02-20 18:06 UTC, tk4chenko approved these changes

2023-02-20 18:25 UTC, Dorogobid requested changes

2023-02-20 18:25 UTC, Dorogobid commented on Skylab/Scenes/OnboardingScene/ViewControllers/OnboardingViewController.swift
> +        viewModel?.openAuthorizationController()
Думаю, що не треба викликати функцію відкриття `AuthorizationController` в `viewDidLoad`. Вважаю, що треба прибрати.

2023-02-21 05:38 UTC, glbrom approved these changes

2023-02-21 06:51 UTC, Dorogobid approved these changes

2023-02-21 07:17 UTC, EvseevIvan approved these changes

2023-02-21 10:06 UTC, Liizza approved these changes

2023-02-21 16:57 UTC, SerhiiMolodets approved these changes

2023-02-26 20:07 UTC, merged